package models

import (
	"time"
)

type Point struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type PostcodeResponseResult struct {
	Postcode  string  `json:"postcode"`
	Country   string  `json:"country"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type PostcodeResponse struct {
	Status int                    `json:"status"`
	Result PostcodeResponseResult `json:"result"`
}

type Library struct {
	Name  string
	Point Point
}

type DistanceLibrary struct {
	Library
	Distance float64
}

// Autogenerated from https://mholt.github.io/json-to-go/ using example response
type AutoGenerated struct {
	Head struct {
		Vars []string `json:"vars"`
	} `json:"head"`
	Results struct {
		Bindings []struct {
			Item struct {
				Type  string `json:"type"`
				Value string `json:"value"`
			} `json:"item"`
			Coord struct {
				Datatype string `json:"datatype"`
				Type     string `json:"type"`
				Value    string `json:"value"`
			} `json:"coord,omitempty"`
			ItemLabel struct {
				XMLLang string `json:"xml:lang"`
				Type    string `json:"type"`
				Value   string `json:"value"`
			} `json:"itemLabel"`
			StartTime struct {
				Datatype string    `json:"datatype"`
				Type     string    `json:"type"`
				Value    time.Time `json:"value"`
			} `json:"startTime,omitempty"`
			EndTime struct {
				Datatype string    `json:"datatype"`
				Type     string    `json:"type"`
				Value    time.Time `json:"value"`
			} `json:"endTime,omitempty"`
		} `json:"bindings"`
	} `json:"results"`
}
